export const CollectionData = [
  {
    id: 1,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 2,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle7',
    authorLogo: 'Ellipse3.png',
    price: '0.218',
  },
  {
    id: 3,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle8',
    authorLogo: 'Ellipse4.png',
    price: '0.218',
  },
  {
    id: 4,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle9',
    authorLogo: 'Ellipse5.png',
    price: '0.218',
  },
  {
    id: 5,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle10',
    authorLogo: 'Ellipse6.png',
    price: '0.218',
  },
  {
    id: 6,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle11',
    authorLogo: 'Ellipse7.png',
    price: '0.218',
  },
  {
    id: 7,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle12',
    authorLogo: 'Ellipse8.png',
    price: '0.218',
  },
  {
    id: 8,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle13',
    authorLogo: 'Ellipse9.png',
    price: '0.218',
  },
];
