export const CollectionData = [
  {
    id: 1,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 2,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 3,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 4,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 5,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 6,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 7,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
  {
    id: 8,
    title: 'World of Women Galaxy',
    author: 'Organization Woman',
    coverImg: 'Rectangle6',
    authorLogo: 'Ellipse2.png',
    price: '0.218',
  },
];
